services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    #environment:
      # RAILS_MASTER_KEY: 
      # WELCOME_MESSAGE: "Welcome to Sample App 118!!!!"
      # DATABASE_URL: postgres://
      # PORT: 80
      # RAILS_ENV: production
